source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'sqlite3'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass'
end
gem 'jquery-rails'
gem "devise", ">= 2.1.2"
gem "cancan", ">= 1.6.8"
gem "rolify", ">= 3.2.0"
gem "simple_form", ">= 2.0.3"

gem 'aws-sdk'
gem 'win32-process'
gem 'ransack'
gem 'kaminari'
gem 'bootstrap-kaminari-views'
gem 'jquery-fileupload-rails'
gem 'carrierwave'
gem 's3_direct_upload'
gem 'streamio-ffmpeg'
gem 'carrierwave-video'
gem 'mini_magick'
gem 'daemons'
gem 'delayed_job_active_record'
gem "whenever", :require => false

gem "rspec-rails", ">= 2.11.0", :group => [:development, :test]
gem "email_spec", ">= 1.2.1", :group => :test
gem "cucumber-rails", ">= 1.3.0", :group => :test, :require => false
gem "database_cleaner", ">= 0.8.0", :group => :test
gem "launchy", ">= 2.1.2", :group => :test
gem "capybara", ">= 1.1.2", :group => :test
gem "factory_girl_rails", ">= 4.1.0", :group => [:development, :test]

group :production do
  gem "capistrano"
end
