source 'http://rubygems.org'

gem 'rails', '3.0.9'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'devise'
gem 'nifty-generators'
gem 'simple_form'
gem 'jquery-rails'

gem 'meta_where'
gem 'meta_search'
gem 'kaminari'
gem 'carrierwave'

