# Fill in your AWS Access Key ID and Secret Access Key
# http://aws.amazon.com/security-credentials

development:
  access_key_id: YOUR_ACCESS_KEY_ID
  secret_access_key: YOUR_SECRET_ACCESS_KEY
  simple_db_consistent_reads: false

production:
  access_key_id: YOUR_ACCESS_KEY_ID
  secret_access_key: YOUR_SECRET_ACCESS_KEY
  simple_db_consistent_reads: true

