# postgresql

development:
  adapter: postgresql
  database: clips_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: clips_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: clips_production
  pool: 5
  timeout: 5000

